frr version 8.4
frr defaults traditional
hostname R1
log stdout
service integrated-vtysh-config
!
router ospf
 ospf router-id 1.1.1.1
 network 10.0.12.0/29 area 0
 network 10.0.13.0/29 area 0
 network 192.168.1.0/24 area 0
!
line vty
!
