frr version 8.4
frr defaults traditional
hostname R3
log stdout
service integrated-vtysh-config
!
router rip
 version 2
 network 10.0.13.0/29
 network 10.0.34.0/29
 network 10.0.35.0/29
 network 192.168.3.0/24
 no auto-summary
!
line vty
!
